# Generated by Django 3.0.3 on 2020-02-18 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True, verbose_name='品名')),
                ('price', models.IntegerField(help_text='単位は円', verbose_name='値段')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '購入者リスト',
                'verbose_name_plural': '購入者リスト',
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(default=datetime.datetime.now, verbose_name='日付')),
                ('number', models.IntegerField(default=1, verbose_name='個数')),
                ('buy_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_moneys.Person', verbose_name='購入者')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_moneys.Item', verbose_name='商品')),
            ],
            options={
                'verbose_name': '購入品リスト',
                'verbose_name_plural': '購入品リスト',
                'db_table': 'Buying',
            },
        ),
    ]
