# Generated by Django 3.0.3 on 2020-02-18 03:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(default=datetime.datetime.now, verbose_name='日付')),
                ('price', models.IntegerField(help_text='単位は円', verbose_name='値段')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_moneys.Item', verbose_name='商品')),
            ],
            options={
                'db_table': 'Buying',
            },
        ),
    ]
