FROM rust:1.39
LABEL maintainer = "shiomoto <ryuusyou3174@gmail.com>"

RUN apt-get update && apt-get install -y gosu
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]